
services:
  - type: web
    name: tg-cost-calc-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_SECRET
        value: calc-987
      - key: EXTERNAL_URL
        sync: false
